version: '3'
services:
  fluentd:
    image: ${USER_NAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:6.4.2
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana:6.4.2
    ports:
      - "5601:5601"
  
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - front_net
      - back_net

networks:
  front_net:
    external:
      name: frontend
  back_net:
    external:
      name: backend